### ISSUE TITLE
Pander with ftable put quotations in output

### ISSUE THREAD

**Issue by walkandride** [Rapporter/pander#266] opened 2016-05-17 16:33 UTC
Character values are in double quotes when an ftable is passed to pander.

`pander(ftable(Titanic, row.vars = 1:3))`

Version:  pander_0.6.0

**Comment by daroczig** [comment] 2016-05-25 00:30
I think this is a duplicate of #242, in short: this should be fixed in the most recent version of the package -- not yet available on CRAN, though. Please confirm and reopen if you still have this issue after `devtools::install_github('rapporter/pander')` -- which should result in:

```r
> pander(ftable(Titanic, row.vars = 1:3))

------- -------- ------- ---------- ----- -----
                          Survived   No    Yes 

 Class    Sex      Age                         

  1st     Male    Child               0     5  

                  Adult              118   57  

         Female   Child               0     1  

                  Adult               4    140 

  2nd     Male    Child               0    11  

                  Adult              154   14  

         Female   Child               0    13  

                  Adult              13    80  

  3rd     Male    Child              35    13  

                  Adult              387   75  

         Female   Child              17    14  

                  Adult              89    76  

 Crew     Male    Child               0     0  

                  Adult              670   192 

         Female   Child               0     0  

                  Adult               3    20  
------- -------- ------- ---------- ----- -----
```

**Closed by daroczig** 2016-05-25 00:30 UTC
