### ISSUE TITLE
Pander doesn't display international characters for me.

### ISSUE THREAD

**Issue by ymer** [Rapporter/pander#340] opened 2019-06-11 10:15 UTC
Example of R studio session:

http://www.jsmp.dk/pander/pander_test.utf8.md.html

**Comment by daroczig** [comment] 2019-06-11 10:53
Can you pls try with the dev version installed from GH? Seems to be a duplicate of #296

**Comment by ymer** [comment] 2019-06-11 16:01
Indeed that fixes it! I thought I had the newest dev, but it turned out I didn't. Apologies for any inconvenience, and thanks for fixing #296.

**Comment by daroczig** [comment] 2019-06-11 16:50
Awesome, thanks for the feedback

**Closed by daroczig** 2019-06-11 16:50 UTC
